#!/usr/bin/env ruby

trap("SIGINT") { exit! }

require 'bundler'
Bundler.setup
require 'html/proofer'
require 'pp'

puts "Using Typhoeus v#{Typhoeus::VERSION}, Ethon v#{Ethon::VERSION}."

proofer_opts = {
  external_only: true,
  verbose:    ARGV.include?('--verbose') || ARGV.include?('-v'),
  typhoeus:   {
    ssl_verifypeer: !ARGV.include?('--no-ssl-verify')
  }
}

puts "Using options:"
pp proofer_opts
puts

begin
  HTML::Proofer.new("./_site", proofer_opts).run
rescue RuntimeError => e
  puts e
  abort
end
