#!/usr/bin/env ruby
# frozen_string_literal: true

trap("SIGINT") { exit! }

require "bundler"
Bundler.setup
require "html-proofer"
require "pp"

puts "Using Typhoeus v#{Typhoeus::VERSION}, Ethon v#{Ethon::VERSION}."

proofer_opts = {
  :verbose    => ARGV.include?("--verbose") || ARGV.include?("-v"),
  :url_ignore => [%r!https://github.com/jekyll/directory/edit/master/_plugins/*!],
  :typhoeus   => {
    :ssl_verifypeer => !ARGV.include?("--no-ssl-verify"),
  },
}

puts "Using options:"
pp proofer_opts
puts

begin
  HTMLProofer.check_directory(File.join("tmp", "site"), proofer_opts).run
rescue RuntimeError => e
  puts e
  abort
end
